### PR TITLE
Update triggers.json

### PR DESCRIPTION
**Pull request by Studnicky**
Business business

### CODE REVIEW

**Comment by okize** [comment]
Thanks for the PR!!

These are great but do you think you could remove the `deploy(|ment)` trigger? my concern is that the word "deploy" is used a lot in the context of releasing code and this could lead to a lot of cats showing up in chats.

**Comment by Studnicky** [comment]
That was exactly why we wanted it, but I understand your concerns.

**Comment by lewisnyman** [comment]
+1 to removing deployment. I find that if these kinds of scripts trigger too often they become annoying instead of surprising and funny. See: https://github.com/github/hubot-scripts/pull/1650

**Comment by Studnicky** [comment]
Fair. I suppose our team is small enough that we wouldn't have minded.

Removed deployment trigger from pull.

**Comment by okize** [comment]
@Studnicky Thanks for making that change!

This has been published in v1.2.7

**Comment by okize** [comment]
@Studnicky if you're interested, I just published v1.3 which would allow you add "deployment" via an environment variable on your hubot instance like so:

```
heroku config:set HUBOT_BUSINESS_CAT_JARGON='deploy(|ment),foo,bar,etc'
```

**Comment by Studnicky** [comment]
Hah nice. I like that.

**Pull request merged**
